### ISSUE TITLE
Brightcove player play button duplicated in IE10 & IE11

### ISSUE THREAD

**Issue by PaulBarnesUK** [qbattersby/oracle-intern#3]
SVG play button being rendered in IE which is showing on top of the web component player's play button.

Suggested solution is to not render an extra element for IE and adjust the styling of the web component play button.

**Comment by qbattersby** [comment]
@PaulBarnesUK Can you give me some details on how/where to recreate this?

**Comment by PaulBarnesUK** [comment]
@qbattersby same with this one, this is now resolved and will be included in my next push

**Comment by qbattersby** [comment]
I will add you as a collab one sec

Quinn Battersby
e// quinn@battersby.ca
t// 226-338-1659
w// www.qbattersby.com

**Comment by PaulBarnesUK** [comment]
Resolved in commit c1de390befd98acbe35a04c71abcd22c3f405053
