### ISSUE TITLE
Text overflowing container on IE10

### ISSUE THREAD

**Issue by PaulBarnesUK** [qbattersby/oracle-intern#4]
Quotes overflow their container on the meet the team page.

Low priority.

**Comment by qbattersby** [comment]
Will have a look at this - due to the length of quote in the green box only option to recreate the grid differently or decrease font size and line-height.

**Comment by PaulBarnesUK** [comment]
@qbattersby I've fixed this one just by adding a max-width to the offending containers, will push code shortly.

**Comment by PaulBarnesUK** [comment]
resolved in commit 61aeb25f9e172b6f48f693586d864d35a80b81e3
