### ISSUE TITLE
Brightcove player time divider styling

### ISSUE THREAD

**Issue by PaulBarnesUK** [qbattersby/oracle-intern#6]
Time divider styling is causing the height of the control bar to grow larger than required on iOS mobile devices.

**Comment by qbattersby** [comment]
@PaulBarnesUK I literally dropped in some of the CSS from the video player section of the Oracle files. Do you have a suggestion for this?

**Comment by PaulBarnesUK** [comment]
@qbattersby Hey yea I'm just working these issues, this one is up next then I'll submit a pull request (or just push if you can add me as a collaborator)

**Comment by PaulBarnesUK** [comment]
resolved in commit 75766861186516320d4bfd408b212fa25a41575b
